
.ifndef ::__VRAM_H_
::__VRAM_H_ = 1

.include "includes/registers.inc"

;; VRAM Map
;; WORD ADDRESSES
PPU_MEMORY_SCREEN_MODE	= BGMODE_MODE1

PPU_MEMORY_BG1_MAP		= $0000
PPU_MEMORY_BG2_MAP		= $0400
PPU_MEMORY_BG3_MAP		= $0800
PPU_MEMORY_BG1_TILES		= $2000
PPU_MEMORY_BG2_TILES		= $1000
PPU_MEMORY_BG3_TILES		= $5000
PPU_MEMORY_OAM_TILES		= $6000

PPU_MEMORY_BG1_SIZE		= BGXSC_SIZE_32X32
PPU_MEMORY_BG2_SIZE		= BGXSC_SIZE_32X32
PPU_MEMORY_BG3_SIZE		= BGXSC_SIZE_32X32

PPU_MEMORY_OAM_SIZE		= OBSEL_SIZE_16_32
PPU_MEMORY_OAM_NAME		= 0

.endif ; __VRAM_H_

; vim: ft=asm:

